name: 'Deploy on IIS'
on:
    push:
        branches: [ main ]
        paths:
            - 'src/HelloDeploy.Web/**'

    workflow_dispatch: # Allow you to run this workflow manually from the Action tab

env:
    PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/src/HelloDeploy.Web/output
    PROJECT_PATH: 'src/HelloDeploy.Web/HelloDeploy.Web.csproj'  
    BUILD_PLATFORM: 'Any CPU'
    BUILD_CONFIGURATION: 'Release'
    APPLICATION_NAME: 'hello_deploy'
    
jobs:
    build-and-package:
        name: 'Build and Package'
        runs-on: windows-latest
        steps:
            - name: 'Checkout'
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
            
            - name: 'Setup MSBuild'
              uses: microsoft/setup-msbuild@v1.1

            - name: 'Setup Nuget Package Restore'
              uses: nuget/setup-nuget@v1

            - name: 'Restore Nuget Packages'
              run: nuget restore ${{ env.PROJECT_PATH }}

            - name: 'Build Application'
              run: |
                msbuild ${{ env.PROJECT_PATH }} /p:Platform="${{ env.BUILD_PLATFORM }}" /p:Configuration="${{ env.BUILD_CONFIGURATION }}" /p:DeployIISAppPath="${{ env.APPLICATION_NAME }}" /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="${{ env.PACKAGE_OUTPUT_DIRECTORY }}" /p:AllowUntrustedCertificate=true /p:PrecompileBeforePublish=true

            - name: 'Upload Package'
              uses: actions/upload-artifact@v3
              with:
                name: ${{ env.APPLICATION_NAME }}
                path: ${{ env.PACKAGE_OUTPUT_DIRECTORY }}
    
    deploy:
      name: 'Deploy on IIS'
      needs: 'build-and-package'
      runs-on: windows-latest
      steps:     
          
            - name: 'Download Package'
              uses: actions/download-artifact@v3
              with:
                name: ${{ env.APPLICATION_NAME }}

            - name: 'Deploy with MsDeploy'
              run: '& "C:/Program Files/IIS/Microsoft Web Deploy V3/msdeploy.exe" -verb:sync -source:package=HelloDeploy.Web.zip -allowUntrusted -dest:auto,computerName="${{ secrets.WEBDEPLOY_COMPUTERNAME }}?site=${{ env.APPLICATION_NAME }}",username="${{ secrets.WEBDEPLOY_USERNAME }}",password="${{ secrets.WEBDEPLOY_PASSWD }}",AuthType="Basic" -verbose -enableRule:DoNotDeleteRule'

            - name: 'Delete Package'
              uses: geekyeggo/delete-artifact@v2
              with:
                name: ${{ env.APPLICATION_NAME }}
